### ISSUE TITLE
Random port selection ports list should accept tuples 

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [ClearcodeHQ/pytest-dbfixtures#100]
Simultaneously with a '3000-4000' or '2300,5000,6000-6030' format of ports accepted by random port feature library should accept ((3000, 4000)) or (2300, 5000, (6000, 6030)) format.

**Comment by pawlowskimichal** [comment]
It may be easier to read if `parse_ports` always interprets sets as distinct available ports and tuples as port ranges.
Like:
`[(20000, 30000), {48889, 50121}]` - range from 20000 to 30000 (including 20000 and 30000) plus ports 4889 and 50121. 

`ports` argument must be a string (then things work as before) or another iterable, list by convention - in that case for each element:
1. If the element is a set, all its elements must be ints. Add its members to the accepted ports.  
2. If it is a tuple, it must always have 2 elements and both elements must be ints, in ascending order. Add ports range.

Also I'd like to see an importable constant like:
`RANDOM_PORT = '?'`

**Comment by wbolster** [comment]
Additionally, a `range()` instance (or `xrange()` on Python 2) could be used here.

**Comment by wbolster** [comment]
And instead of having a magical `RANDOM_PORT` constant to avoid hardcoding a `?` character, a `random_port=True` might be more clear.
