### ISSUE TITLE
Executors still running after tests fail

### ISSUE THREAD

**Issue by mruwnik** [ClearcodeHQ/pytest-dbfixtures#101]
If an error occurs during tests, pytest exists with an error message, but any started executors carry on running

**Comment by pwilczynskiclearcode** [comment]
Might be related to https://github.com/ClearcodeHQ/mirakuru/blob/master/mirakuru/base.py
Does this issue always happen?

**Comment by fizyk** [comment]
@mruwnik what kind of error? Could you duplicate, or describe the case? I hadn't had problems so far like that?

**Comment by mruwnik** [comment]
sorry - it sometime happens when something terrible happens in the tests, but happens a lot more often when stopping tasks with ctrl+c. It seems like no stop signal is sent to the processes so they keep on running after the test process has been stopped. I think @pwilczynskiclearcode is probably right in this being related to mirakuru, as the HttpProcesses don't stop. It doesn't always happen, but it's often enough to have to manually kill -9 the processes, as they use up ports

**Comment by pwilczynskiclearcode** [comment]
Next version of mirakuru https://github.com/ClearcodeHQ/mirakuru should handle these issues.
