### ISSUE TITLE
Scope of factory

### ISSUE THREAD

**Issue by tomislater** [ClearcodeHQ/pytest-dbfixtures#103]
I want to run ``redisdb`` as a session scope, but I can't.

I think we can use something like:
    
    def redisdb(process_fixture_name, db=None, strict=True, scope='function'):
        ....
        @pytest.fixture(scope=scope)
        def redisdb_factory(request):
            """

**Comment by fizyk** [comment]
Good. That way you start each test with fresh, empty database, and avoid
quite a few race conditions, and weird tests depending on others tests.

That's the reason we removed scope parameter from mysql fixture.

Grzegorz Śliwiński
Sent on the road.

I want to run redisdb as a session scope, but I can't.

I think we can use something like:

def redisdb(process_fixture_name, db=None, strict=True, scope='function'):
    ....
    @pytest.fixture(scope=scope)
    def redisdb_factory(request):
        """

—
Reply to this email directly or view it on GitHub
<https://github.com/ClearcodeHQ/pytest-dbfixtures/issues/103>.
