### ISSUE TITLE
Remove full paths to binaries in dbfixtures.conf

### ISSUE THREAD

**Issue by robmessick** [ClearcodeHQ/pytest-dbfixtures#107]
The "dbfixtures.conf" file contains full paths to the the server binaries (e.g. /usr/bin/redis-server). The defaults should be changed to the binary name (redis-server). pytest-dbfixtures should trust that the user has the PATH configured correctly in their test execution environment.

**Comment by pwilczynskiclearcode** [comment]
We could change it into: take redis from PATH if not specified precisely.

**Comment by fizyk** [comment]
Will be dealt by #160 split packages will have config options for command line and pytest.ini, and everyone will be able to change executable easily.
