### ISSUE TITLE
redisdb fixture shouldn't force decode_responses=True

### ISSUE THREAD

**Issue by ulope** [ClearcodeHQ/pytest-dbfixtures#116]
Currently the redisdb fixture hardcodes the parameter `decode_responses` to `True`. This differs from StrictRedis' default and causes test breakage when dealing with binary data.

I'd suggest to remove the parameter entirely or at least allow it to be configured via a factory argument.

**Comment by fizyk** [comment]
This issue was moved to ClearcodeHQ/pytest-redis#14
