### ISSUE TITLE
Support using a custom elasticsearch configuration directory

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/pytest-dbfixtures#122]
```
        command_exec = '''
            {deamon} -p {pidfile} --http.port={port}
            --path.home={home_path}  --default.path.logs={logs_path}
            --default.path.work={work_path}
            --default.path.conf=/etc/elasticsearch
[...]
```
So configuration is taken from the system-wide `/etc/elasticsearch` directory. This prevents packages using pytest-dbfixtures from using custom configuration included in their repositories, maintained via pull requests and used on CI where the test suite has no permission to write in `/etc`. (It can be useful to customize e.g. log verbosity for tests.)

**Comment by vcavel** [comment]
Do you have any updates on this?

**Comment by fizyk** [comment]
We'd gladly accept pull requests :)

**Comment by fizyk** [comment]
This issue was moved to ClearcodeHQ/pytest-elasticsearch#28
