### ISSUE TITLE
Spectacular failure running the mongodb example

### ISSUE THREAD

**Issue by jayennis22** [ClearcodeHQ/pytest-dbfixtures#126]
I'm new to py.test and dbfixtures and getting this spectacular failure which seems to be in bowels of the factory code.  py.test itself seems to work fine.  Any hints as to what it might be?  FWIW, this is running on an ARM processor, but I shouldn't think that would matter.

Thanks!

================================================== ERRORS ==================================================
_______________________________________ ERROR at setup of test_mongo _______________________________________

request = <SubRequest 'mongodb' for <Function 'test_mongo'>>

    @pytest.fixture
    def mongodb_factory(request):
        """
            #. Get pymongo module and config.
            #. Get connection to mongo.
            #. Drop collections before and after tests.

            :param FixtureRequest request: fixture request object
            :rtype: pymongo.connection.Connection
            :returns: connection to mongo database
            """
>       proc_fixture = get_process_fixture(request, process_fixture_name)

../venv/local/lib/python2.7/site-packages/pytest_dbfixtures/factories/mongo.py:121:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../venv/local/lib/python2.7/site-packages/pytest_dbfixtures/utils.py:73: in get_process_fixture
    process = request.getfuncargvalue(process_name)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1385: in getfuncargvalue
    return self._get_active_fixturedef(argname).cached_result[0]
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1402: in _get_active_fixturedef
    result = self._getfuncargvalue(fixturedef)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1448: in _getfuncargvalue
    val = fixturedef.execute(request=subrequest)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1914: in execute
    self.yieldctx)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1839: in call_fixture_func
    res = fixturefunc(**kwargs)
../venv/local/lib/python2.7/site-packages/pytest_dbfixtures/factories/mongo.py:92: in mongo_proc_fixture
    mongo_executor.start()
../venv/local/lib/python2.7/site-packages/mirakuru/base.py:393: in start
    super(Executor, self).start()
../venv/local/lib/python2.7/site-packages/mirakuru/base.py:184: in start
    env=env
/usr/lib/python2.7/subprocess.py:710: in __init__
    errread, errwrite)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <subprocess.Popen object at 0xb62610d0>
args = ['/usr/bin/mongod', '--bind_ip', '127.0.0.1', '--port', '27069', '--dbpath', ...]
executable = '/usr/bin/mongod', preexec_fn = <built-in function setsid>, close_fds = False, cwd = None
env = {'HOME': '/home/jennis', 'LANG': 'en_GB.UTF-8', 'LD_LIBRARY_PATH': '/usr/local/lib', 'LOGNAME': 'jennis', ...}
universal_newlines = True, startupinfo = None, creationflags = 0, shell = False, to_close = set([11, 12])
p2cread = 9, p2cwrite = 11, c2pread = 12, c2pwrite = 13, errread = None, errwrite = None

    def _execute_child(self, args, executable, preexec_fn, close_fds,
                       cwd, env, universal_newlines,
                       startupinfo, creationflags, shell, to_close,
                       p2cread, p2cwrite,
                       c2pread, c2pwrite,
                       errread, errwrite):
        """Execute program (POSIX version)"""

        if isinstance(args, types.StringTypes):
            args = [args]
        else:
            args = list(args)

        if shell:
            args = ["/bin/sh", "-c"] + args
            if executable:
                args[0] = executable

        if executable is None:
            executable = args[0]

        def _close_in_parent(fd):
            os.close(fd)
            to_close.remove(fd)

        # For transferring possible exec failure from child to parent
        # The first char specifies the exception type: 0 means
        # OSError, 1 means some other error.
        errpipe_read, errpipe_write = self.pipe_cloexec()
        try:
            try:
                gc_was_enabled = gc.isenabled()
                # Disable gc to avoid bug where gc -> file_dealloc ->
                # write to stderr -> hang.  http://bugs.python.org/issue1336
                gc.disable()
                try:
                    self.pid = os.fork()
                except:
                    if gc_was_enabled:
                        gc.enable()
                    raise
                self._child_created = True
                if self.pid == 0:
                    # Child
                    try:
                        # Close parent's pipe ends
                        if p2cwrite is not None:
                            os.close(p2cwrite)
                        if c2pread is not None:
                            os.close(c2pread)
                        if errread is not None:
                            os.close(errread)
                        os.close(errpipe_read)

                        # When duping fds, if there arises a situation
                        # where one of the fds is either 0, 1 or 2, it
                        # is possible that it is overwritten (#12607).
                        if c2pwrite == 0:
                            c2pwrite = os.dup(c2pwrite)
                        if errwrite == 0 or errwrite == 1:
                            errwrite = os.dup(errwrite)

                        # Dup fds for child
                        def _dup2(a, b):
                            # dup2() removes the CLOEXEC flag but
                            # we must do it ourselves if dup2()
                            # would be a no-op (issue #10806).
                            if a == b:
                                self._set_cloexec_flag(a, False)
                            elif a is not None:
                                os.dup2(a, b)
                        _dup2(p2cread, 0)
                        _dup2(c2pwrite, 1)
                        _dup2(errwrite, 2)

                        # Close pipe fds.  Make sure we don't close the
                        # same fd more than once, or standard fds.
                        closed = { None }
                        for fd in [p2cread, c2pwrite, errwrite]:
                            if fd not in closed and fd > 2:
                                os.close(fd)
                                closed.add(fd)

                        if cwd is not None:
                            os.chdir(cwd)

                        if preexec_fn:
                            preexec_fn()

                        # Close all other fds, if asked for - after
                        # preexec_fn(), which may open FDs.
                        if close_fds:
                            self._close_fds(but=errpipe_write)

                        if env is None:
                            os.execvp(executable, args)
                        else:
                            os.execvpe(executable, args, env)

                    except:
                        exc_type, exc_value, tb = sys.exc_info()
                        # Save the traceback and attach it to the exception object
                        exc_lines = traceback.format_exception(exc_type,
                                                               exc_value,
                                                               tb)
                        exc_value.child_traceback = ''.join(exc_lines)
                        os.write(errpipe_write, pickle.dumps(exc_value))

                    # This exitcode won't be reported to applications, so it
                    # really doesn't matter what we return.
                    os._exit(255)

                # Parent
                if gc_was_enabled:
                    gc.enable()
            finally:
                # be sure the FD is closed no matter what
                os.close(errpipe_write)

            # Wait for exec to fail or succeed; possibly raising exception
            # Exception limited to 1M
            data = _eintr_retry_call(os.read, errpipe_read, 1048576)
        finally:
            if p2cread is not None and p2cwrite is not None:
                _close_in_parent(p2cread)
            if c2pwrite is not None and c2pread is not None:
                _close_in_parent(c2pwrite)
            if errwrite is not None and errread is not None:
                _close_in_parent(errwrite)

            # be sure the FD is closed no matter what
            os.close(errpipe_read)

        if data != "":
            try:
                _eintr_retry_call(os.waitpid, self.pid, 0)
            except OSError as e:
                if e.errno != errno.ECHILD:
                    raise
            child_exception = pickle.loads(data)
>           raise child_exception
E           OSError: [Errno 2] No such file or directory

/usr/lib/python2.7/subprocess.py:1335: OSError

**Comment by tomislater** [comment]
Hmm, did you install mongo?

Could you put example of your code?

**Comment by jayennis22** [comment]
The following prints Ok without asserting, so I believe mongo and pymongo are working:
```python
from pymongo import MongoClient

client = MongoClient()
db = client['db_test']
test_data = {
    "test1": "test1",
}
db.test.insert_one(test_data)
assert db.test.find_one()['test1'] == 'test1'
print "Ok"
```

The dbfixtures code that is failing comes from the current github example:
```python
from pytest_dbfixtures import factories

def test_mongo(mongodb):
    test_data = {
        "test1": "test1",
    }

    db = mongodb['test_db']
    db.test.insert(test_data)
    assert db.test.find_one()['test1'] == 'test1'
```
I'm new to mongo, pymongo and py.test, so I certainly could be missing something simple.  Thanks for your help!

**Comment by tomislater** [comment]
Could you check where you have ``mongod``?

Look at this line: https://github.com/ClearcodeHQ/pytest-dbfixtures/blob/master/pytest_dbfixtures/conf/dbfixtures.conf#L9

Maybe you have exec in other place.

**Comment by jayennis22** [comment]
That's a help... I had not yet discovered the conf file.  More clues:
* my mongo is installed and running in a docker container with port 27017 mapped back onto the host.  The host does not have docker installed, hence there is no /usr/bin/mongod.
* I changed the port to 27017 and ran it again with the following error output:
```
============================================================================== ERRORS ==============================================================================
___________________________________________________________________ ERROR at setup of test_mongo ___________________________________________________________________

request = <SubRequest 'mongodb' for <Function 'test_mongo'>>

    @pytest.fixture
    def mongodb_factory(request):
        """
            #. Get pymongo module and config.
            #. Get connection to mongo.
            #. Drop collections before and after tests.

            :param FixtureRequest request: fixture request object
            :rtype: pymongo.connection.Connection
            :returns: connection to mongo database
            """
>       proc_fixture = get_process_fixture(request, process_fixture_name)

../venv/local/lib/python2.7/site-packages/pytest_dbfixtures/factories/mongo.py:121:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../venv/local/lib/python2.7/site-packages/pytest_dbfixtures/utils.py:73: in get_process_fixture
    process = request.getfuncargvalue(process_name)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1385: in getfuncargvalue
    return self._get_active_fixturedef(argname).cached_result[0]
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1402: in _get_active_fixturedef
    result = self._getfuncargvalue(fixturedef)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1448: in _getfuncargvalue
    val = fixturedef.execute(request=subrequest)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1914: in execute
    self.yieldctx)
../venv/local/lib/python2.7/site-packages/_pytest/python.py:1839: in call_fixture_func
    res = fixturefunc(**kwargs)
../venv/local/lib/python2.7/site-packages/pytest_dbfixtures/factories/mongo.py:92: in mongo_proc_fixture
    mongo_executor.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pytest_dbfixtures.executors.TCPExecutor: "/usr/bin/m..." 0xb6aa06d0L>

    def start(self):
        """
            Start executor with additional checks.

            Checks if previous executor isn't running then start process
            (executor) and wait until it's started.
            """
        if self.pre_start_check():
            # Some other executor (or process) is running with same config:
>           raise AlreadyRunning(self)
E           AlreadyRunning: Executor <pytest_dbfixtures.executors.TCPExecutor: "/usr/bin/mongod --bind_ip 127.0.0.1 --port 27017 --dbpath /tmp/mongo_pytest_fixtureTwu90i --logpath /tmp/mongo.27017.log "> seems to be already running. It looks like the previous executor process hasn't been terminated or killed. Also there might be some completely different service listening on 27017 port.

../venv/local/lib/python2.7/site-packages/mirakuru/base.py:391: AlreadyRunning
```
It looks like dbfixtures expects to be able to start its own instance of mongod and can't because it is not installed on the host.  Is that a prerequisite when mongo is running elsewhere?

Thanks,
Jay

**Comment by fizyk** [comment]
Hi @jayennis22

Basically every database dbfixture is using is an instance created by dbfixtures itself. It does that to have completely clear database, with very little effort required to actually prepare database instance and all access except for having required executable.

**Comment by jayennis22** [comment]
So perhaps I am missing a key point.  I believe that you are saying that dbfixture requires a local mongo instance.  I'll give that a try.

**Comment by jayennis22** [comment]
This addresses my issue.  Perhaps the documentation could be improved to make clear the requirement that the database must be installed on the same machine where the tests run?

Thanks very much for your help!

**Comment by tomislater** [comment]
Good point, we should do it.
