### ISSUE TITLE
mysql client fixture teardown hangs if connections exist

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/pytest-dbfixtures#139]
`mysql_conn.query('DROP DATABASE IF EXISTS %s' % mysql_db)` involves waiting for all connections to the database to be closed. This hangs the test if e.g. the test developer adds a session-scoped fixture running a process that accesses the database. The mysql client fixture should have a time limit for this query and raise an exception if it's exceeded, or check if connections remain and raise a more specific exception.

**Comment by mmaslowskicc** [comment]
PostgreSQL raises an exception in such cases.

**Comment by fizyk** [comment]
This issue was moved to ClearcodeHQ/pytest-mysql#9
