### ISSUE TITLE
xdist and random ports possible issue

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [ClearcodeHQ/pytest-dbfixtures#147]
We delete data folders of mysql, redis, etc. when database is down and port is released.
In case of using xdist, the other worker may try to use the port again so it will try to write to the directory which the first fixture hasn't yet cleaned up.

**Comment by mmaslowskicc** [comment]
At least for `postgresql_proc`, we delete the directory before creating it in `init_postgresql_database`. I'm not sure of a way to test if such problem can occur.

**Comment by fizyk** [comment]
@mmaslowskicc we'd have to test functions responsible manually. outside of a fixture run actually.
