### ISSUE TITLE
Support dropping tables instead of the database at PostgreSQL client fixture teardown

### ISSUE THREAD

**Issue by mmaslowskicc** [ClearcodeHQ/pytest-dbfixtures#188]
Nearly any bug in a project using PostgreSQL and having test service processes running from session-scoped fixtures causes a test failure cascade or hang, with errors about dropping databases with existing connections.

I think these might work if we (optionally, to keep the otherwise safer current default) drop tables and not the database between tests.

**Comment by fizyk** [comment]
If we go deep enough, the services might be even affected by the lack of data if we decide to ie clear tables, and not drop them,

In my opinion, this should be handled in those services. maybe a signal to reconnect in between tests?

**Comment by mmaslowskicc** [comment]
In the easy case of services using a connection pool, having no running requests between tests but keeping open connections, this works and they are not affected by lack of data.

A signal needs additional work to close connections in the test process, in all services, and to wait until these connections are closed (with just closing them after every request I had strange problems with small changes in a test causing a connection leak).

**Comment by mmaslowskicc** [comment]
I'm not sure which approach is more compatible with my idea of test fixtures working when testing incorrect code; I also don't want to consider connection pooling a bug.

**Comment by mmaslowskicc** [comment]
As discussed, this is too risky (badly written services will pass tests and will have some yet unknown objects kept between tests). A more reliable solution for my problem is disconnecting all connections to the database, dropping the database, and fixing the application to reconnect then.
