### ISSUE TITLE
Don't read my.cfn config file by default (MySQL)

### ISSUE THREAD

**Issue by tomislater** [ClearcodeHQ/pytest-dbfixtures#193]
It might be difficult to debug what is going on, so I propose to use `--no-defaults` flag in `mysqld_safe` command (https://github.com/ClearcodeHQ/pytest-dbfixtures/blob/master/src/pytest_dbfixtures/factories/mysql.py#L121). Maybe it is not the best approach to resolve this problem.

Another idea in my head: provide a flag `--defaults-file`? and use a file from this param. If user does not use this flag, use `--no-defaults` flag.

From documentation (http://dev.mysql.com/doc/refman/5.6/en/mysqld-safe.html#option_mysqld_safe_defaults-file):

> --no-defaults
> Do not read any option files. This must be the first option on the command line if it is used.

**Comment by fizyk** [comment]
Actually being able to set all possible values for fixture, would be much better, and we would impose this separation from my.cnf file completely.

**Comment by fizyk** [comment]
However this would be blocked by #160

**Comment by fizyk** [comment]
This issue was moved to ClearcodeHQ/pytest-mysql#8
