### ISSUE TITLE
mysql_install_db fails with MySQL >= 5.7.5

### ISSUE THREAD

**Issue by DonnchaC** [ClearcodeHQ/pytest-dbfixtures#207]
### Bug

The `mysql_install_db` Perl script was [replaced](http://dev.mysql.com/doc/refman/5.7/en/mysql-install-db.html) with a C++ implementation in MySQL 5.7.5. This C++ version does not have the `--tmpfile` option which causes an error when it is called in `init_mysql_directory()`.

```
$ /usr/bin/mysql_install_db --user=user --datadir=/tmp/pytest-mysql-Ey_Qr4/mysqldata_3307 --tmpdir=/tmp/pytest-mysql-Ey_Qr4 
mysql_install_db: [ERROR] unknown variable 'tmpdir=/tmp/pytest-mysql-Ey_Qr4'
2016-10-26 21:48:24 [ERROR]   Unrecognized options
```

The `--tmpdir` option was introduced in pytest-dbfixtures 0.16.0, however `mysql_install_db` still fails for me without that option (with MySQL 5.7.16). I'm not sure if this is just a local problem. Regardless `mysql_install_db` is deprecated.

```
$ /usr/bin/mysql_install_db --user=user --datadir=/tmp/pytest-mysql-Ey_Qr4/mysqldata_3307                
2016-10-26 21:49:15 [WARNING] mysql_install_db is deprecated. Please consider switching to mysqld --initialize
2016-10-26 21:49:15 [ERROR]   Can't locate the server executable (mysqld).
```

MySQL 5.7.6 deprecates the `mysql_install_db` command and introduces a `mysqld --initialize` command as a replacement. 

`pytest-dbfixtures` needs to determine the local `mysqld` version and initialize the database with correct choice between `mysql --initialize` or `mysql_install_db`.
### Temporary Fix

Here is a fix that I am using until this problem gets resolved. It might be useful for others who run into this problem.

``` python
try:
    pytest_dbfixtures.utils.get_process_fixture(request, 'mysql_proc')
except subprocess.CalledProcessError:
    # Fix for MySQL versions >= 5.7.6 which use `mysqld --initialize` instead
    # of `mysql_install_db`. This fix can be removed when pytest_dbfixtures
    # supports MySQL >= 5.7.6 is updated.
    logsdir = request.config.getvalue('logsdir')
    logfile_path = os.path.join(logsdir, 'mysql-server.log')
    mysql_proc_5_7 = pytest_dbfixtures.factories.mysql_proc(
        init_executable="mysqld --initialize-insecure "
                        "--log-error=" + logfile_path)
    mysql_proc_5_7(request)
```

**Comment by fizyk** [comment]
This issue was moved to ClearcodeHQ/pytest-mysql#7
