### ISSUE TITLE
ModuleNotFoundError: No module named 'pytest_dbfixtures.plugin'

### ISSUE THREAD

**Issue by ParasBotadra** [ClearcodeHQ/pytest-dbfixtures#228]
I am trying to use pytest with my local instance of dynamodb. I installed pytest and pytest-dbfixtures in my working environment, but when I tried to run my tests it gives me ModuleNotFoundError: No module named 'pytest_dbfixtures.plugin'.
Please help me to fix this issue so that I can proceed with my testing.

**Comment by fizyk** [comment]
https://pypi.org/project/pytest-dynamodb/ is where the dynamodb is being developed. Rather use that plugin directly, not dbfixtures itself.
