### ISSUE TITLE
documentation on usage for postgresql?

### ISSUE THREAD

**Issue by hallaj** [ClearcodeHQ/pytest-dbfixtures#60]
Hey, I was browsing through and found this dbfixtures and was testing it out. Could you append a HOWTO for PostgreSQL? I've tried the following but it just went idle;

``` python
def test_connect(postgresql):
    """tests postgresql connection"""
    cur = postgresql.cursor()
    cur.execute("SELECT * FROM users")
    postgresql.commit()
    cur.close()
```

Nothing happens and the test is waiting for test_connect. Looking at the background process, it did spin up a new PostgreSQL server on port 5433. So I decided to try another test

``` python
def test_postgresql(postgresql):
    """this should just fail and not wait for anything"""
    assert False
```

Even with the following code, it still hangs up and waits. Can you point out what I'm missing? Thanks.

**Comment by brunsgaard** [comment]
@hallaj, #105, the part about the log destination in my PR may solve your problem.

**Comment by hallaj** [comment]
@brunsgaard Just applied the patch and it's still stuck. I suppose it's a different issue.

**Comment by brunsgaard** [comment]
@hallaj okay :(

**Comment by fizyk** [comment]
please see if https://pypi.python.org/pypi/pytest-postgresql works for you. if you still have any problems here.
